### ISSUE TITLE
Broken with 2.2.0 release of arr-includes

### ISSUE THREAD

**Issue by bdentino** [inspect-js/is-async-function#17]
arr-includes now exports as default, which breaks this package on new installs.

**Comment by tunnckoCore** [comment]
Ahhh. Thanks. I migrated `arr-includes` in december to the `opensource` monorepo and it seems that broke this package.

I'll check what I can do.

**Comment by tunnckoCore** [comment]
Published `1.3.0` stable.

Thanks.
