### ISSUE TITLE
next major?: support for AsyncFunction / better `function-arguments`

### ISSUE THREAD

**Issue by tunnckoCore** [inspect-js/is-async-function#18]
First, we could support the new `async function fn() {}`.

And second: better arguments parser, because currently it returns `false` if you have function like `function someFn(a, opts = { foo: 1 }, callback)`

This is because `function-arguments` is pretty simple, intentionally and seems like it doesn't understand "default params", which already landed in the nodejs's core, that's why some of the `fs` tests were failing.

_Or probably not, we have `parse-function` for more advanced stuff._

**Comment by tunnckoCore** [comment]
@ljharb, let's support both the old-school `(a, b, callback)` and `async function`? Or your thing is just for async/await? Cuz... in treality the old school is async function too so :laughing: Oh, i have `is-callback-function` too i think haahhaha

**Comment by ljharb** [comment]
My intention would be to only support syntactic `async function`s - functions that always return a promise and can never throw a sync exception.

**Comment by tunnckoCore** [comment]
hm. okay, no problem.

but any ideas on names for the current thing? I may need it some time, and seems like others are using it too and they may not be satisfied with the coming v2.

**Comment by tunnckoCore** [comment]
Okay, added you on npm too.

**Comment by ljharb** [comment]
ah hmm - so one option for them is to just stay on v1 - it won't be `npm deprecated` or anything - but another possible name is `is-asynchronous-function`?

Thanks! I'll update and publish a v2 later today.

**Comment by ljharb** [comment]
Something we could do:
1. Do not ever fork is-async-function or make a repo with that name, or it’ll break redirects
2. I can start v2 on an entirely bare branch, leaving v1 only accessible via tags
3. I can fork this to my personal user, then rename it to “is-asynchronous-function” or whatever you like
4. I can bounce that fork to you
5. You can develop the is-asynchronous-function package directly off of the last published v1, on a default branch not named “main”

That way, there’s never a conflict between the forks, the redirects aren’t broken, git history is maximally retained, and you can keep working on the v1 functionality under a new name, in your own repo.

A bit convoluted, but it should work. Thoughts?

**Comment by ljharb** [comment]
v2 is published, on https://github.com/inspect-js/is-async-function/tree/main.

https://github.com/inspect-js/is-async-function/tree/master remains, as do all the pre-v2 tags.
